import type { SupportIntent } from './types'

export const supportKnowledgeBase: SupportIntent[] = [
  {
    id: 'payment-methods',
    category: 'buyer',
    keywords: ['pay', 'payment', 'paystack', 'mobile money', 'card', 'bank transfer', 'how to pay', 'accepted payment', 'which payment', 'payment method', 'pay with', 'payment option', 'checkout payment'],
    patterns: ['how (can|do) i pay', 'what (payment|method)', 'accepted payment', 'pay with', 'payment option', 'which (payment|card|method)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/payment-policy/page.tsx and app/faq/faq-client.tsx (FAQ #7)',
    response: 'Dhream Market processes all payments through Paystack, our secure centralized payment system. We accept all major credit/debit cards, mobile money, and bank transfers. You do not pay vendors directly — all payments are made through our platform at checkout. Paystack transaction fees may apply.',
  },
  {
    id: 'refund-policy',
    category: 'buyer',
    keywords: ['refund', 'return', 'money back', 'get my money back', 'return policy', 'return item'],
    patterns: ['how (do|can) i (get a|request a) refund', 'refund policy', 'return (an|my) item', 'can i (get a|have a) refund'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/refund/page.tsx (Sections 2-7)',
    response: 'Products may be returned within 7 days of receiving them if they do not match the description, are damaged or defective on arrival, or if you received the wrong item. Returns must be initiated by contacting the vendor through your order. The vendor reviews requests within 3 business days. Refunds are processed within 5-7 business days after approval, credited to your original payment method. Items that cannot be returned include opened personal care products, digital goods, final sale items, and products returned after the 7-day window. The vendor covers return shipping for defective or wrong items; change-of-mind returns are the customer\'s responsibility.',
  },
  {
    id: 'delivery-shipping',
    category: 'buyer',
    keywords: ['delivery', 'shipping', 'how long', 'arrive', 'track', 'delivery time', 'ship', 'shipping cost'],
    patterns: ['how long (does|will) (delivery|shipping|it take)', 'when (will|does) (my|the) (order|item) (arrive|ship|deliver)', 'track (my|the) (order|package)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 7: Shipping and Delivery) and app/faq/faq-client.tsx (FAQ #10)',
    response: 'Shipping costs and delivery times vary by vendor and shipping method. Standard delivery typically takes 3-7 business days. Vendors are responsible for shipping products to the address provided. You can track your order by going to your Dashboard > Orders and clicking on any order to see its current status. We are not responsible for delays caused by shipping carriers.',
  },
  {
    id: 'how-to-register-vendor',
    category: 'general',
    keywords: ['register', 'sign up', 'become a vendor', 'vendor account', 'sell on', 'start selling', 'open a store'],
    patterns: ['how (do|can) i (become|register as|sign up as) (a )?vendor', 'how (do|can) i (start|begin) selling', 'how (to|do i) open (a )?store'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #4) and app/terms/page.tsx (Section 4: Vendor Terms)',
    response: 'To become a vendor on Dhream Market: (1) Register an account and select "Vendor" as your role during sign-up. (2) Complete your profile and set up your store. (3) Submit your store for verification. Our team reviews vendor applications within 1-2 business days. Vendors must provide accurate product descriptions, price products fairly, fulfill orders promptly, maintain appropriate business licenses, and comply with all applicable laws.',
  },
  {
    id: 'how-to-list-product',
    category: 'general',
    keywords: ['list product', 'add product', 'upload product', 'create listing', 'post product', 'sell product', 'add item'],
    patterns: ['how (do|can) i (add|list|upload) (a )?product', 'how (to|do i) (create|post) (a )?listing', 'how (do|can) i sell (a )?product'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #5)',
    response: 'To list a product: navigate to your Vendor Dashboard > Products, click "Add Product", fill in the product details, upload images (JPG, PNG, or WebP, under 10MB each) via Cloudinary, set your pricing and stock levels, then publish. Ensure product descriptions and images are accurate and that pricing is fair.',
  },
  {
    id: 'vendor-payout-timing',
    category: 'general',
    keywords: ['payout', 'get paid', 'when do i get paid', 'payment schedule', 'receive money', 'vendor earnings', 'withdraw'],
    patterns: ['when (do|will) i (get|receive) (my )?payout', 'how (often|long) (do|does) (payout|payment) (take|come)', 'vendor (payout|earnings|payment)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 16: Marketplace Payment Processing & Vendor Payout Policy) and app/faq/faq-client.tsx (FAQ #6)',
    response: 'All customer payments are processed through Dhream Market\'s centralized Paystack account. Vendors do NOT receive payments directly from customers. Dhream Market aggregates and reconciles completed sales before payouts are made. Vendors receive 100% of the product price minus platform commission (if applicable) and payment processing fees. Payouts are processed monthly via bank transfer. Dhream Market reserves the right to determine payout schedules, holding periods, and settlement timelines. Payouts may be temporarily held in cases of suspicious activity, fraud investigation, disputes, policy violations, or compliance reviews. It is the vendor\'s responsibility to ensure their payout banking details are accurate.',
  },
  {
    id: 'how-to-contact-support',
    category: 'general',
    keywords: ['contact', 'support', 'help', 'reach', 'human', 'speak to someone', 'call', 'email'],
    patterns: ['how (do|can) i (contact|reach|speak to) (support|someone|you)', 'contact (support|us|dhream market)', 'talk to (support|a human|someone)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 17: Contact Information) and app/faq/faq-client.tsx',
    response: 'You can reach our support team via WhatsApp at https://wa.me/447869840464/ for immediate assistance. You can also visit our Contact page or email us at support@dhreamarket.com. For FAQ answers, browse our Help Centre at /faq.',
  },
  {
    id: 'how-to-reset-password',
    category: 'general',
    keywords: ['reset password', 'forgot password', 'change password', 'password reset', 'can\'t login', 'cannot login', 'locked out'],
    patterns: ['how (do|can) i (reset|change|recover) (my )?password', 'forgot (my )?password', 'can\'?t (log|sign) ?in', 'locked (out|account)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #17) and app/forgot-password/ route',
    response: 'To reset your password: click "Forgot Password" on the login page, enter the email address associated with your account, and follow the reset link sent to your inbox. The reset link expires in 1 hour. If you don\'t receive the email, check your spam folder or contact support.',
  },
  {
    id: 'order-status-inquiry',
    category: 'buyer',
    keywords: ['order status', 'my order', 'track order', 'order update', 'where is my order', 'order details', 'check order'],
    patterns: ['(what|how) (is|are) (my )?(order|orders)', 'track (my )?(order|package)', 'status of (my )?order', 'where is (my )?order'],
    requiresAuth: true,
    isDynamic: true,
    dynamicType: 'order_status',
    sourceFile: 'Dynamic lookup: Prisma Order model (app/api/checkout/route.ts auth pattern)',
    response: '__DYNAMIC_ORDER_STATUS__',
  },
  {
    id: 'vendor-payout-status',
    category: 'general',
    keywords: ['payout status', 'my payout', 'vendor payment', 'payout history', 'how much have i been paid', 'payout details'],
    patterns: ['(what|how) (is|are) (my )?payout', 'payout (status|history|detail)', 'how much (have|did) i (get )?paid', 'vendor (payment|payout) status'],
    requiresAuth: true,
    isDynamic: true,
    dynamicType: 'vendor_payout_status',
    sourceFile: 'Dynamic lookup: Prisma VendorPayout model (app/terms/page.tsx Section 16)',
    response: '__DYNAMIC_VENDOR_PAYOUT__',
  },
  {
    id: 'account-creation',
    category: 'general',
    keywords: ['create account', 'sign up', 'register', 'register account', 'make an account', 'new account', 'account setup'],
    patterns: ['how (do|can) i (create|make|set up) (an?) account', 'how (do|can) i (sign|register) (up|in)', 'create account', '(need|want) to create an account'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #1)',
    response: 'To create an account, click the "Sign Up" button in the top right corner of the homepage. Fill in your email, create a password, and select "Customer" as your role during registration. After submitting, check your email to verify your address — this completes the registration process and unlocks full access to your dashboard.',
  },
  {
    id: 'place-order',
    category: 'buyer',
    keywords: ['place order', 'buy product', 'order from', 'how to order', 'checkout', 'buy item', 'purchase'],
    patterns: ['how (do|can) i (place|make) (an?) (order|purchase)', 'how (do|can) i (buy|checkout)', 'order (from|on) (your|the) (site|store|market)', '(where|how) to (buy|order)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #2)',
    response: 'To place an order: (1) Browse products by category or search. (2) Click "Add to Cart" on any item you want. (3) Go to your cart and click "Proceed to Checkout." (4) Enter your shipping address and contact details. (5) Select Paystack as your payment method and complete the secure payment. You\'ll receive an order confirmation email once your payment is processed.',
  },
  {
    id: 'payment-declined',
    category: 'buyer',
    keywords: ['payment declined', 'card declined', 'payment failed', 'transaction failed', 'decline', 'payment not working', 'card not working'],
    patterns: ['(why|what) (is|was|) my payment (declined|failed|rejected)', 'card (declined|rejected|not (working|accepted))', 'payment (did not|won\'?t|cannot|can\'?t) go through', '(transaction|payment) failed'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #9)',
    response: 'Payment declines can occur for several reasons: insufficient funds in your account, incorrect card details (expiry date, CVV), your bank flagging the transaction as potentially fraudulent, or temporary Paystack service issues. To resolve: verify your card details, try a different payment method (another card, mobile money, or bank transfer), ensure sufficient funds, or contact your bank. You can retry checkout once the issue is addressed.',
  },
  {
    id: 'order-modification-cancellation',
    category: 'buyer',
    keywords: ['cancel order', 'modify order', 'change order', 'edit order', 'remove item from order', 'update order', 'order cancellation'],
    patterns: ['how (do|can) i (cancel|modify|change|edit) (my )?order', '(cancel|modify|change|edit) order', '(request|need) to (cancel|modify) my order'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #11)',
    response: 'Orders can only be modified or cancelled within 1 hour of placement, and only if they haven\'t already entered processing or shipping. To request changes: go to your Dashboard > Orders, find the relevant order, and if the timeframe allows, select "Cancel Order" or contact the seller directly through the order page. After 1 hour or once the order is in processing, cancellation requests must go through the support team for review. Refunds for approved cancellations are processed within 5-7 business days.',
  },
  {
    id: 'damaged-order',
    category: 'buyer',
    keywords: ['damaged item', 'broken item', 'damaged order', 'received broken', 'item broken', 'defective product', 'wrong item', 'missing item'],
    patterns: ['(what|how) if (my |the )(order|item) (is|arrives) (damaged|broken|defective)', '(received|got) (damaged|broken|wrong) (item|order|product)', '(item|product) (arrived|came) (damaged|broken|defective)'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #12)',
    response: 'If your order arrives damaged, broken, or with the wrong item: (1) Take clear photos of the damage or incorrect item immediately upon receipt. (2) Contact the seller through your order page within 48 hours, attaching the photos. (3) The seller should respond and arrange a return, replacement, or refund. If the seller does not respond within 48 hours, contact our support team for intervention. Keep all original packaging until the issue is resolved.',
  },
  {
    id: 'vendor-verification-timing',
    category: 'vendor',
    keywords: ['store verification', 'verification time', 'how long to verify', 'vendor approval', 'store approval', 'when will my store be verified', 'verification status'],
    patterns: ['(how long|when) (does|will) (store|vendor) verification (take|last)', 'why (is|my) store verification (taking|slow)', '(store|vendor) (approval|verification) status'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #13)',
    response: 'Store verification typically takes 1-2 business days after you submit your application. Delays may occur if the support team needs additional documentation or if there are discrepancies in the information provided. You’ll receive an email notification once verification is complete. To check your status, visit your Vendor Dashboard where the verification status is displayed. If your verification is taking longer than expected, contact support with your vendor ID for an update.',
  },
  {
    id: 'vendor-verification-docs',
    category: 'vendor',
    keywords: ['verification documents', 'required documents', 'id verification', 'business registration', 'proof of business', 'vendor documents', 'what documents needed'],
    patterns: ['(what|which) (documents|id) (are|do i need|required) for (store|vendor) verification', 'vendor (verification|kyc) documents', '(proof|need) (id|business registration)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #14)',
    response: 'For vendor verification, we require: (1) A valid government-issued photo ID — passport, driver\'s license, or national ID card. (2) Proof of business registration, if applicable to your product category. (3) Additional business licenses may be required for certain product categories (e.g., electronics, health products). Upload these documents during the vendor onboarding process. Ensure documents are clear, unexpired, and not cropped. All information is kept secure and used solely for verification purposes.',
  },
  {
    id: 'featured-vendor-program',
    category: 'vendor',
    keywords: ['featured vendor', 'featured store', 'how to get featured', 'promoted vendor', 'featured listing', 'become featured'],
    patterns: ['(how|what) (do|does) it take to be(come|) (a )?featured vendor', 'how (to|do i) get my store (featured|promoted)', '(featured|promotion) vendor (program|listing)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #15)',
    response: 'Featured vendor status is a recognition awarded to top-performing stores that consistently meet high standards: (1) Excellent customer ratings (4.5+ average). (2) Fast and reliable shipping with high fulfillment rates. (3) High-quality products and accurate descriptions. (4) Prompt customer service response times. (5) Minimal disputes or chargebacks. The admin team also manually features vendors based on merit and marketplace contribution. We review all active vendors monthly and notify selected stores via email.',
  },
  {
    id: 'featured-vendor-benefits',
    category: 'vendor',
    keywords: ['featured vendor benefits', 'featured benefits', 'promotional benefits', 'store promotion', 'visibility benefits', 'premium placement'],
    patterns: ['(what|which) (are|is|) (the|) (benefits|advantages|perks) of (being |a )?featured', '(featured|promotion) (benefits|advantages)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #16)',
    response: 'Featured vendors receive exclusive benefits including: (1) Premium placement on the marketplace homepage and category pages. (2) Enhanced visibility in search results with a priority boost. (3) Special "Featured" badge displayed on their storefront and listings. (4) Priority access to promotional campaigns and seasonal sales events. (5) Dedicated support line for faster response times. (6) Early access to new platform features. These benefits help increase your store\'s reach and conversion rates.',
  },
  {
    id: 'update-profile',
    category: 'general',
    keywords: ['update profile', 'edit profile', 'change profile', 'profile information', 'update account', 'edit account'],
    patterns: ['(how|what) (do|can) i (update|edit|change) (my )?(profile|account information)'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #18)',
    response: 'To update your profile: (1) Log in to your account. (2) Navigate to your Dashboard > Settings. (3) From there you can update your name, email, phone number, shipping address, and profile picture. (4) Click "Save Changes" to apply. For vendors, the Settings page also allows you to manage your store name, store description, business details, and payout banking information. Changes take effect immediately.',
  },
  {
    id: 'delete-account',
    category: 'general',
    keywords: ['delete account', 'remove account', 'cancel account', 'close account', 'account deletion'],
    patterns: ['(how|what) (do|can) i (delete|remove|close|cancel) (my )?account'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #19)',
    response: 'To request account deletion: contact our support team with your account email and a brief explanation. Please note: account deletion is permanent and irreversible. It will remove all your personal data, order history, reviews, saved addresses, and wishlist items. Any content you\'ve created as a vendor (store, listings) will also be removed. Before proceeding, download any order history or data you wish to keep. The deletion process is completed within 30 days of your request being verified.',
  },
  {
    id: 'website-loading-issue',
    category: 'general',
    keywords: ['website not loading', 'page not loading', 'website down', 'site not working', 'slow website', 'loading error', 'page error'],
    patterns: ['(website|site) (is|not) (not )?(loading|working|down|slow)', '(page|site) (won\'?t|cannot|can\'?t) load', 'website (issue|problem|error)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #20)',
    response: 'If the website is not loading or running slowly: (1) Clear your browser cache and cookies, then reload. (2) Disable browser extensions that might interfere (ad blockers, privacy tools). (3) Try a different browser or device. (4) Check your internet connection. (5) If the issue persists on both desktop and mobile, it may be a platform outage. Check our social media for status updates. If you still need help, contact support with the specific error message you see.',
  },
  {
    id: 'upload-image-issue',
    category: 'vendor',
    keywords: ['upload image', 'image upload failed', 'can\'t upload image', 'upload error', 'picture upload', 'product image upload'],
    patterns: ['(can\'?t|unable|problem) (upload|adding) (image|picture|photo)'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #21)',
    response: 'To upload product images successfully: (1) Ensure your image is in JPG, PNG, or WebP format. (2) The file must be under 10MB per image. (3) Check your internet connection — uploads require a stable connection. (4) Try a different browser if the upload fails repeatedly. Images are uploaded via our Cloudinary integration. If uploads continue to fail, try reducing the image resolution or file size. Contact support if the issue persists after trying these steps.',
  },
  {
    id: 'email-notifications',
    category: 'general',
    keywords: ['email not working', 'not receiving email', 'email notifications', 'no email', 'missing emails', 'spam folder', 'inbox'],
    patterns: ['(not|isn\'?t|can\'?t) (receiving|getting) (email|emails|email notifications)', '(email|emails) (not|didn\'?t) (arrive|come|arrive in inbox)'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #22)',
    response: 'If you\'re not receiving email notifications: (1) Check your spam or junk folder first — our emails may have been filtered there. (2) Add support@dhreamarket.com to your email contacts or safe sender list. (3) Verify your email address is correct in your account settings (Dashboard > Settings). (4) Ensure your email inbox isn\'t full. (5) Check if your email provider is blocking our messages and add an exception. If you still don\'t receive emails after these steps, contact support for manual assistance.',
  },
  {
    id: 'shipping-cost',
    category: 'buyer',
    keywords: ['shipping cost', 'delivery cost', 'how much shipping', 'shipping fee', 'delivery fee', 'postage cost', 'shipping price'],
    patterns: ['(how much|what|how) (is|does) (shipping|delivery|postage) (cost|fee|price)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 7: Shipping and Delivery)',
    response: 'Shipping costs vary by vendor location, product size/weight, and selected shipping method. During checkout, shipping fees are calculated and displayed before you complete payment — you can see the exact amount on the checkout page. Some vendors offer free shipping on orders above a certain amount (displayed on their store). We never charge shipping separately from your order total; all costs are shown upfront at checkout.',
  },
  {
    id: 'discount-code',
    category: 'buyer',
    keywords: ['discount code', 'promo code', 'coupon', 'voucher', 'promotional code', 'discount', 'promo', 'coupon code'],
    patterns: ['(how|can|where) (do|can|to) i (apply|use) (a )?(discount|promo|coupon|voucher) code', '(discount|promo|coupon) (code|not working|expired)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (General marketplace policies)',
    response: 'To use a discount or promo code: (1) At checkout, look for the "Have a promo code?" field. (2) Enter your code exactly as provided (case-sensitive). (3) Click "Apply" — the discount will be reflected in your order total. Promo codes are time-sensitive and may have minimum purchase amounts or category restrictions. If a code doesn\'t work, check the expiration date and terms. Only one promo code can be applied per order. For vendor-specific codes, ensure the vendor participates in the promotion.',
  },
  {
    id: 'wishlist',
    category: 'buyer',
    keywords: ['wishlist', 'save for later', 'save item', 'favorite product', 'bookmark', 'wishlist item', 'saved items'],
    patterns: ['(how|can) i (add|save) (to|an item to) (my )?wishlist', '(save for later|save item|wishlist)', '(where|how) is (my )?wishlist'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx and app/terms/page.tsx',
    response: 'To add items to your wishlist: (1) While browsing or viewing a product, click the heart icon on the product card or product page. (2) The item will be saved to your wishlist. (3) Access your wishlist anytime by going to your Dashboard > Wishlist. To remove an item, click the heart icon again or use the "Remove" option in your wishlist. Items in your wishlist can be quickly added to cart when you\'re ready to purchase. Wishlist items are synced across devices when logged in.',
  },
]

export const WHATSAPP_SUPPORT_LINK = 'https://wa.me/447869840464/'

export const SUPPORT_EMAIL = 'support@dhreamarket.com'
