import type { SupportIntent } from './types'

export const supportKnowledgeBase: SupportIntent[] = [
  {
    id: 'payment-methods',
    category: 'buyer',
    keywords: ['pay', 'payment', 'paystack', 'mobile money', 'card', 'bank transfer', 'how to pay', 'accepted payment', 'which payment', 'payment method', 'pay with', 'payment option', 'checkout payment'],
    patterns: ['how (can|do) i pay', 'what (payment|method)', 'accepted payment', 'pay with', 'payment option', 'which (payment|card|method)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/payment-policy/page.tsx and app/faq/faq-client.tsx (FAQ #7)',
    response: 'Dhream Market processes all payments through Paystack, our secure centralized payment system. We accept all major credit/debit cards, mobile money, and bank transfers. You do not pay vendors directly — all payments are made through our platform at checkout. Paystack transaction fees may apply.',
  },
  {
    id: 'refund-policy',
    category: 'buyer',
    keywords: ['refund', 'return', 'money back', 'get my money back', 'return policy', 'return item'],
    patterns: ['how (do|can) i (get a|request a) refund', 'refund policy', 'return (an|my) item', 'can i (get a|have a) refund'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/refund/page.tsx (Sections 2-7)',
    response: 'Products may be returned within 7 days of receiving them if they do not match the description, are damaged or defective on arrival, or if you received the wrong item. Returns must be initiated by contacting the vendor through your order. The vendor reviews requests within 3 business days. Refunds are processed within 5-7 business days after approval, credited to your original payment method. Items that cannot be returned include opened personal care products, digital goods, final sale items, and products returned after the 7-day window. The vendor covers return shipping for defective or wrong items; change-of-mind returns are the customer\'s responsibility.',
  },
  {
    id: 'delivery-shipping',
    category: 'buyer',
    keywords: ['delivery', 'shipping', 'how long', 'arrive', 'track', 'delivery time', 'ship', 'shipping cost'],
    patterns: ['how long (does|will) (delivery|shipping|it take)', 'when (will|does) (my|the) (order|item) (arrive|ship|deliver)', 'track (my|the) (order|package)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 7: Shipping and Delivery) and app/faq/faq-client.tsx (FAQ #10)',
    response: 'Shipping costs and delivery times vary by vendor and shipping method. Standard delivery typically takes 3-7 business days. Vendors are responsible for shipping products to the address provided. You can track your order by going to your Dashboard > Orders and clicking on any order to see its current status. We are not responsible for delays caused by shipping carriers.',
  },
  {
    id: 'how-to-register-vendor',
    category: 'general',
    keywords: ['register', 'sign up', 'become a vendor', 'vendor account', 'sell on', 'start selling', 'open a store'],
    patterns: ['how (do|can) i (become|register as|sign up as) (a )?vendor', 'how (do|can) i (start|begin) selling', 'how (to|do i) open (a )?store'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #4) and app/terms/page.tsx (Section 4: Vendor Terms)',
    response: 'To become a vendor on Dhream Market: (1) Register an account and select "Vendor" as your role during sign-up. (2) Complete your profile and set up your store. (3) Submit your store for verification. Our team reviews vendor applications within 1-2 business days. Vendors must provide accurate product descriptions, price products fairly, fulfill orders promptly, maintain appropriate business licenses, and comply with all applicable laws.',
  },
  {
    id: 'how-to-list-product',
    category: 'general',
    keywords: ['list product', 'add product', 'upload product', 'create listing', 'post product', 'sell product', 'add item'],
    patterns: ['how (do|can) i (add|list|upload) (a )?product', 'how (to|do i) (create|post) (a )?listing', 'how (do|can) i sell (a )?product'],
    requiresAuth: true,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #5)',
    response: 'To list a product: navigate to your Vendor Dashboard > Products, click "Add Product", fill in the product details, upload images (JPG, PNG, or WebP, under 10MB each) via Cloudinary, set your pricing and stock levels, then publish. Ensure product descriptions and images are accurate and that pricing is fair.',
  },
  {
    id: 'vendor-payout-timing',
    category: 'vendor',
    keywords: ['payout', 'get paid', 'when do i get paid', 'payment schedule', 'receive money', 'vendor earnings', 'withdraw'],
    patterns: ['when (do|will) i (get|receive) (my )?payout', 'how (often|long) (do|does) (payout|payment) (take|come)', 'vendor (payout|earnings|payment)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 16: Marketplace Payment Processing & Vendor Payout Policy) and app/faq/faq-client.tsx (FAQ #6)',
    response: 'All customer payments are processed through Dhream Market\'s centralized Paystack account. Vendors do NOT receive payments directly from customers. Dhream Market aggregates and reconciles completed sales before payouts are made. Vendors receive 100% of the product price minus platform commission (if applicable) and payment processing fees. Payouts are processed monthly via bank transfer. Dhream Market reserves the right to determine payout schedules, holding periods, and settlement timelines. Payouts may be temporarily held in cases of suspicious activity, fraud investigation, disputes, policy violations, or compliance reviews. It is the vendor\'s responsibility to ensure their payout banking details are accurate.',
  },
  {
    id: 'how-to-contact-support',
    category: 'general',
    keywords: ['contact', 'support', 'help', 'reach', 'human', 'speak to someone', 'call', 'email'],
    patterns: ['how (do|can) i (contact|reach|speak to) (support|someone|you)', 'contact (support|us|dhream market)', 'talk to (support|a human|someone)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/terms/page.tsx (Section 17: Contact Information) and app/faq/faq-client.tsx',
    response: 'You can reach our support team via WhatsApp at https://wa.me/447869840464/ for immediate assistance. You can also visit our Contact page or email us at support@dhreamarket.com. For FAQ answers, browse our Help Centre at /faq.',
  },
  {
    id: 'how-to-reset-password',
    category: 'general',
    keywords: ['reset password', 'forgot password', 'change password', 'password reset', 'can\'t login', 'cannot login', 'locked out'],
    patterns: ['how (do|can) i (reset|change|recover) (my )?password', 'forgot (my )?password', 'can\'?t (log|sign) ?in', 'locked (out|account)'],
    requiresAuth: false,
    isDynamic: false,
    sourceFile: 'app/faq/faq-client.tsx (FAQ #17) and app/forgot-password/ route',
    response: 'To reset your password: click "Forgot Password" on the login page, enter the email address associated with your account, and follow the reset link sent to your inbox. The reset link expires in 1 hour. If you don\'t receive the email, check your spam folder or contact support.',
  },
  {
    id: 'order-status-inquiry',
    category: 'buyer',
    keywords: ['order status', 'my order', 'track order', 'order update', 'where is my order', 'order details', 'check order'],
    patterns: ['(what|how) (is|are) (my )?(order|orders)', 'track (my )?(order|package)', 'status of (my )?order', 'where is (my )?order'],
    requiresAuth: true,
    isDynamic: true,
    dynamicType: 'order_status',
    sourceFile: 'Dynamic lookup: Prisma Order model (app/api/checkout/route.ts auth pattern)',
    response: '__DYNAMIC_ORDER_STATUS__',
  },
  {
    id: 'vendor-payout-status',
    category: 'vendor',
    keywords: ['payout status', 'my payout', 'vendor payment', 'payout history', 'how much have i been paid', 'payout details'],
    patterns: ['(what|how) (is|are) (my )?payout', 'payout (status|history|detail)', 'how much (have|did) i (get )?paid', 'vendor (payment|payout) status'],
    requiresAuth: true,
    isDynamic: true,
    dynamicType: 'vendor_payout_status',
    sourceFile: 'Dynamic lookup: Prisma VendorPayout model (app/terms/page.tsx Section 16)',
    response: '__DYNAMIC_VENDOR_PAYOUT__',
  },
]

export const WHATSAPP_SUPPORT_LINK = 'https://wa.me/447869840464/'

export const SUPPORT_EMAIL = 'support@dhreamarket.com'
